ShopApp.MVC/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopApp.DataAccess.Models;
using ShopApp.DataAccess.Other;
using ShopApp.DataAccess.Repository.IRepository;

namespace ShopApp.MVC.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = Helpers.Admin_Role)] //video 120
	public class ProductsController : Controller
	{
		private readonly IUnitOfWork _context;
		private readonly IWebHostEnvironment _webHostEnvironment;

		public ProductsController(IUnitOfWork context, IWebHostEnvironment webHostEnvironment)
		{
			_context = context;
			_webHostEnvironment = webHostEnvironment;
		}

		// GET: Admin/Products
		//public async Task<IActionResult> Index()
		//{
		//    var shopAppMVCContext = _context.Product.Include(p => p.Category);
		//    return View(await shopAppMVCContext.ToListAsync());
		//}
		public async Task<IActionResult> Index()
		{
			var query = _context.ProductRepository.GetAllAsync(include_properties: "Category");
			return View(await query);
		}

		// GET: Admin/Products/Details/5
		public async Task<IActionResult> Details(Guid? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			//    var product = await _context.Product
			//        .Include(p => p.Category)
			//        .FirstOrDefaultAsync(m => m.Id == id);
			var product = await _context.ProductRepository.GetAsync(expression: m => m.Id == id, include_properties: "Category");
			if (product == null)
			{
				return NotFound();
			}

			return View(product);
		}


		// GET: Admin/Products/Create
		public IActionResult Create()
		{
			ViewData["CategoryId"] = new SelectList(_context.CategoryRepository.GetAll(), "Id", "Name");
			return View();
		}


		// POST: Admin/Products/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,CategoryId,Name,Description,ListPrice,SalePrice,ImageUrl")] Product product, IFormFile? file)
		{
			if (ModelState.IsValid)
			{
				product.Id = Guid.NewGuid();
				product.ImageUrl = CreateImage(file);

				_context.ProductRepository.Add(product);
				await _context.SaveAsync();

				return RedirectToAction(nameof(Index));
			}
			ViewData["CategoryId"] = new SelectList(_context.CategoryRepository.GetAll(), "Id", "Name", product.CategoryId);

			return View(product);
		}


		// GET: Admin/Products/Edit/5
		public async Task<IActionResult> Edit(Guid? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var product = await _context.ProductRepository.GetAsync(expression: m => m.Id == id);
			//var product = await _context.Product.FindAsync(id);
			if (product == null)
			{
				return NotFound();
			}
			ViewData["CategoryId"] = new SelectList(_context.CategoryRepository.GetAll(), "Id", "Name", product.CategoryId);
			return View(product);
		}

		// POST: Admin/Products/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(Guid id, [Bind("Id,CategoryId,Name,Description,ListPrice,SalePrice,ImageUrl")] Product product, IFormFile? file)
		{
			if (id != product.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					if (file != null)
					{
						DeleteImage(product.ImageUrl);
						product.ImageUrl = CreateImage(file);
					}

					//_context.Update(product);
					//await _context.SaveChangesAsync();
					_context.ProductRepository.Update(product);
					await _context.SaveAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!ProductExists(product.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			//ViewData["CategoryId"] = new SelectList(_context.Set<Category>(), "Id", "Name", product.CategoryId);
			ViewData["CategoryId"] = new SelectList(_context.CategoryRepository.GetAll(), "Id", "Name", product.CategoryId);
			return View(product);
		}

		// GET: Admin/Products/Delete/5
		public async Task<IActionResult> Delete(Guid? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			//var product = await _context.Product
			//    .Include(p => p.Category)
			//    .FirstOrDefaultAsync(m => m.Id == id);
			var product = await _context.ProductRepository.GetAsync(expression: m => m.Id == id, include_properties: "Category");
			if (product == null)
			{
				return NotFound();
			}

			return View(product);
		}

		// POST: Admin/Products/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(Guid id)
		{
			//var product = await _context.Product.FindAsync(id);
			var product = await _context.ProductRepository.GetAsync(expression: m => m.Id == id);
			if (product != null)
			{
				DeleteImage(product.ImageUrl);

				//_context.Product.Remove(product);
				_context.ProductRepository.Remove(product);
			}

			//await _context.SaveChangesAsync();
			await _context.SaveAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool ProductExists(Guid id)
		{
			return _context.ProductRepository.Exists(expression: m => m.Id == id);
			//return _context.Product.Any(e => e.Id == id);
		}



		private string? CreateImage(IFormFile? file)
		{
			if (file == null)
			{
				return null;
			}

			//string filename = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
			string extension = Path.GetExtension(file.FileName);
			string filename = Path.ChangeExtension(Path.GetRandomFileName(), extension);
			string file_path = Path.Combine(_webHostEnvironment.WebRootPath, @"images\products", filename);

			using (var file_stream = new FileStream(file_path, FileMode.Create))
			{
				file.CopyTo(file_stream);
			}

			//product.ImageUrl = @"\images\product\" + filename;
			return filename;
		}

		private void DeleteImage(string? image_name)
		{
			if (string.IsNullOrEmpty(image_name))
			{
				return;
			}

			//string old_image_path = Path.Combine(product_path, product.ImageUrl.TrimStart('\\'));
			//string old_image_path = Path.GetFileName(product.ImageUrl);
			string file_path = Path.Combine(_webHostEnvironment.WebRootPath, @"images\products", image_name);

			if (System.IO.File.Exists(file_path))
			{
				System.IO.File.Delete(file_path);
			}

		}



		#region API Calls

		[HttpGet]

        public async Task<IActionResult> GetAll()
        {
			IEnumerable<Product> products = await _context.ProductRepository.GetAllAsync(include_properties: "Category");


			//List<Product> products = _context.ProductRepository.GetAll(include_properties: "Category").ToList();

			return Json( new {data = products});
            //return View(await query);
        }

        #endregion


    }
}

ShopApp.MVC/Areas/Customer/Controllers/CartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopApp.DataAccess.Models;
using ShopApp.DataAccess.Repository.IRepository;
using System.Linq.Expressions;

namespace ShopApp.MVC.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

		public CartController(IUnitOfWork context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        public async Task<IActionResult> Index()
        {
			var query = _context.CartRepository.GetAllAsync();
			return View(await query);
        }

        public IActionResult AddProduct(Guid id)
        {
            Product product = _context.ProductRepository.Get(x => x.Id == id);

            AddProductToCart(product);

            return View();
        }







        public void AddProductToCart(Product product)
        {
            if (User.Identity == null || product == null)
            {
                return;
            }

            IdentityUser user = _context.CartRepository.Context.Users.Where(user => user.UserName == User.Identity.Name).FirstOrDefault();

            //EndUser user = _context.EndUserRepository.Get(user => user.UserName == User.Identity.Name);

            if (user == null)
            {
                return;
            }

            Cart cart = _context.CartRepository.Get(cart => cart.UserId == user.Id);
            if (cart == null)
            {
                cart = new()
                {
                    UserId = user.Id,
                };
                _context.CartRepository.Add(cart);
                _context.CartRepository.Context.SaveChanges();
            }

            ProductCount product_count = new()
            {
                Product = product,
                Count = 1
            };
            cart.ProductCounts.Add(product_count);
            
        }
	}
}

ShopApp.MVC/Areas/Customer/Controllers/EndUserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopApp.DataAccess.Models;
using ShopApp.DataAccess.Repository.IRepository;

namespace ShopApp.MVC.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class EndUserController : Controller
    {
        private readonly IUnitOfWork _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

		public EndUserController(IUnitOfWork context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
			var query = _context.EndUserRepository.GetAllAsync();
			return View(await query);
        }


	}
}

ShopApp.MVC/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopApp.MVC.Data;
using ShopApp.MVC.Models;

namespace ShopApp.MVC.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DisplayOrder")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DisplayOrder")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            if (category != null)
            {
                _context.Category.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.Id == id);
        }
    }
}

ShopApp.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopApp.MVC</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_minty.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopApp.MVC.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.8/css/dataTables.dataTables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShopApp.MVC</a>
                @* <a asp-area="" asp-controller="Home" asp-action="Index">ShopApp.MVC</a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Customer
                            </a>
                            <ul class="dropdown-menu">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="Products" asp-action="Index">Products</a>
                                @* <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a> *@
@*                                 <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li> *@
                            </ul>
						</li>

                        @* video 120 *@
                        @if (User.IsInRole(Helpers.Admin_Role))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Categories" asp-action="Index">Categories</a>
                                    </li>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>

                                </ul>
                            </li>
                        }

                        <li class ="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-cart"></i> (0)
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="EndUser" asp-action="Index">
                                Users
                            </a>
                        </li>

@* 						<li class="nav-item">
							<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li> *@


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ShopApp.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="//cdn.datatables.net/2.0.8/js/dataTables.min.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ShopApp.MVC/Views/Shared/_NotificationPartial.cshtml
@if (TempData["success"] != null)
{
    <h2>@TempData["success"]</h2>
}
@if (TempData["error"] != null)
{
    <h2>@TempData["error"]</h2>
}